Implement gdnlib generation
utopia-rise/godot-kotlin pull request #138
Opened 2020-04-25 12:00 UTC by raniejade

2020-04-25 12:40 UTC, chippmann requested changes

2020-04-25 12:40 UTC, chippmann commented on plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/GenerateLibrary.kt
> +open class GenerateLibrary : DefaultTask() {
I'm more for `GenerateGdns`. `GenerateLibrary` sounds like you actually generate a whole lib, which is not the case

2020-04-25 12:44 UTC, chippmann approved these changes

2020-04-25 17:16 UTC, piiertho commented on plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/GenerateGdnlib.kt
> +            Platform.IOS_X64 -> "iOS.64" // not sure if Godot even supports this
Godot supports it, you can remove the comment :)

2020-04-25 17:20 UTC, piiertho requested changes

2020-04-25 17:20 UTC, piiertho commented on plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/GenerateGdnlib.kt
> +            Platform.IOS_X64 -> "iOS.64" // not sure if Godot even supports this
Godot supports it, you can remove the comment :)
https://docs.godotengine.org/fr/latest/development/compiling/compiling_for_ios.html

2020-04-28 21:10 UTC, piiertho approved these changes

2020-04-29 09:57 UTC, merged