Rename Platform to GodotPlatform and improve setup guide
utopia-rise/godot-kotlin pull request #220
Opened 2020-08-08 05:08 UTC by raniejade

2020-08-08 12:36 UTC, CedNaru approved these changes

2020-08-08 15:57 UTC, chippmann requested changes
A few comments otherwise awesome work!

2020-08-08 15:57 UTC, chippmann commented on docs/src/doc/setup/gradle.md
> +import godot.global.*
`import godot.global.*` is unused but `import godot.core.GD` is missing

2020-08-08 15:57 UTC, chippmann commented on docs/src/doc/setup/gradle.md
>  Now we can trigger a build.
IMO `org.gradle.jvmargs=-Xmx3G` inside `gradle.properties` is missing as the first build failed for me because of running out of memory

2020-08-08 15:59 UTC, chippmann commented on docs/src/doc/setup/gradle.md
>  Now we can trigger a build.
maybe also an explanation why we need more memory would be good in an info box or something like that

2020-08-08 16:40 UTC, piiertho approved these changes

2020-08-09 02:19 UTC, chippmann approved these changes

2020-08-09 02:39 UTC, merged