Streamline idea importing
utopia-rise/godot-kotlin pull request #224
Opened 2020-08-09 02:29 UTC by raniejade

This adds a `parent` directory in our project, which should be used when importing the project into IntelliJ IDEA. This will ensure that we get proper code highlighting in the included builds. I also moved the root `.idea/*` into `parent/.idea/*`

2020-08-09 07:29 UTC, chippmann requested changes
With this change everything works like a charm. But some comments:
- I'm no fan of the name `parent`. TBH I currently don't really have a better idea. Maybe `rootProject` or `projectRoot`?
- IMHO some documentation is missing. Because if one imports the project like you normally do, not parent is imported only `godot-kotlin`is imported.

2020-08-09 07:29 UTC, chippmann commented on parent/.idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Why is this file commited?

2020-08-09 07:29 UTC, chippmann commented on parent/.idea/gradle.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Why is this file commited?

2020-08-09 07:29 UTC, chippmann commented on parent/.idea/jarRepositories.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Why is this file commited?

2020-08-09 07:29 UTC, chippmann commented on parent/.idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Why is this file commited?

2020-08-09 07:29 UTC, chippmann commented on parent/.idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Why is this file commited?

2020-08-09 07:34 UTC, raniejade commented
I'm not sure, I'm not a fan of `rootProject` or `projectRoot` either. Maybe `ide` or `idea`?

2020-08-09 08:40 UTC, raniejade commented
I'll add the docs later, lets merge this to unblock @CedNaru

2020-08-09 09:21 UTC, raniejade commented on build-root/settings.gradle.kts
> +includeBuild("../") {
@piiertho here, this will import the root project

2020-08-09 09:24 UTC, piiertho approved these changes

2020-08-09 10:44 UTC, CedNaru approved these changes

2020-08-09 18:07 UTC, chippmann approved these changes
Ok for me

2020-08-11 08:42 UTC, raniejade commented
Closing this in favor of #230

2020-08-11 08:42 UTC, closed without merging