Feature/registration default value improvement
utopia-rise/godot-kotlin pull request #63
Opened 2020-03-07 08:54 UTC by chippmann

This resolves #53.
This improves the default value registration for properties by leveraging the psi system to read the default value from code.
A user can now write:
```
@RegisterProperty(true)
var playerBodyNodePath = NodePath("Entities/Player/PlayerBody")
```
To register properties. The default value will in this example be `godot.core.NodePath("Entities/Player/PlayerBody")`.

Also this removes the possibility of defining default values for signals.
This is done because it didn't work in the first place and it seems not supported anymore anyways. I found no way to make it work and the cpp bindings for example don't seem to support it either. The same can be achieved anyways through binds in the `connect` method.
I someone has an idea of how tho make this work, I'm open for suggestions.
What i tried:
- Passing the individual default arguments one by one to the vararg `default_args` in the `register_signal` function.
- Passing all of them together to the `default_arg` parameter as a GDArray

Both ways if the signal was emitted with no arguments, the `args` value we get from godot is null.

I opted for removing this feature as i also didn't find it in the cpp binding, nor did i find any sort of documentation about it.

2020-03-07 12:27 UTC, raniejade commented
Interesting approach, but what happens when you have:

```kotlin
val pathStr = "Entities/Player/PlayerBody"

@RegisterProperty
val path = NodePath(pathStr)
```

2020-03-07 12:55 UTC, chippmann commented
@raniejade At the moment this does not work. It would leave to an unresolved reference.
I should probably mention this in the docs as well.
It is possible to follow the reference but i didn't do this for now.

2020-03-07 13:21 UTC, raniejade commented
I don't think the reference should be followed because you might be accessing a property of `this` which is not available during registration time.

```
@RegisterProperty
val path = NodePath(getSomePath())
```

2020-03-07 13:44 UTC, chippmann commented
True.
But i should check in the future if the element at that position is a valid assignment. But for now i think its ok if i just mention this in the docs.

2020-03-08 07:58 UTC, piiertho approved these changes
Thanks for the enhancement and debug ! :)

2020-03-08 08:03 UTC, piiertho commented
> True.
> But i should check in the future if the element at that position is a valid assignment. But for now i think its ok if i just mention this in the docs.

oops, looked to changes before looking to discussion. Can you add this to documentation for the moment, then it should be ok for now. Thanks @raniejade for highlighting this problem.

2020-03-08 08:05 UTC, piiertho requested changes
Add missing doc.
Also, now that #61 is merged, maybe we can have longer reflexion on problem on accessing variables from this at registration time ?

2020-03-08 09:04 UTC, chippmann commented
@piiertho sorry i don't get what you mean

2020-03-08 09:45 UTC, chippmann commented
Damn i also managed to push `platform=linux` in the samples. I'll remove that as well.

2020-03-08 13:25 UTC, piiertho commented
@chippmann i was meaning that maybe we can take more time to think about the problem @raniejade mentionned.

2020-03-09 09:17 UTC, chippmann commented
@piiertho I see. I'm generally fine with this idea. But i would like to merge it first anyways as it removes the not working signal default arguments we for now have included.
But i could extract that in a separate PR so we don't need to merge this one for now if you want. That would be fine as well i guess.
Anyways i will stale my work on #39 and #52 until i completely improved this.

2020-03-09 18:58 UTC, chippmann commented
@piiertho and @raniejade 
My current implementation correctly detects the following wrongly defined registered properties:
```
val blubb = ""
@RegisterProperty(true)
var test1 = NodePath(blubb)

@RegisterProperty(true)
var test2 = Vector3::x

private val ref = 300
@RegisterProperty(true)
var test3 = this.ref

private fun getRef() = 300
@RegisterProperty(true)
var function = this.getRef()

lateinit var velocity: Vector2
@RegisterProperty(true)
var test4 = velocity.x
```

Do you have any other mistakes in inititalisation the user might be able to do?
lateinits, val, and by lazy was already handled

2020-03-10 12:48 UTC, piiertho commented
@chippmann what about others delegate properties ? Does that works ?

2020-03-10 12:49 UTC, piiertho commented
Mmmh maybe that's a stupid question, as we don't know how custom delegates works...

2020-03-10 13:49 UTC, chippmann commented
It should work. But to test it, you could make an example how you would write it and i try it as well. Regarding delegates i just tried by lazy.

2020-03-15 02:06 UTC, raniejade commented
We need to make sure that the exposed property is `Variant` compatible (i.e can be converted to a `Variant`).

I initially disliked the approach as it can cause unexpected errors.
- referencing values from `this` which is not available during registration time
- not all types can be exposed to Godot.

But I think with some IDE inspections we can easily educate users about this caveat.

On my binding I go around the caveats above by:

> - referencing values from `this` which is not available during registration time

registration happens manually and outside of `this` context. So the default value can't reference any values from `this`.

> - not all types can be exposed to Godot.

By using delegates and only implemented it for types that are `Variant` compatible. This means that I don't have to rely on a custom compiler plugin to do the checks for me - the kotlin compiler does it out of the box.

I wonder if we can come up with a compromise of the two approach?

```kotlin
@RegisterProperty
val myProperty by property<Int> { ... }
```

Pros:
- automatic registration
- no need for custom compiler plugin to check if type can be exposed

Cons:
- The issue with referencing `this` is still there.

With the mentioned cons above, we can just do the check in the compiler plugin. i.e check that the lambda is `non-capturing`. The kotlin does the same thing for `Worker.execute` and `staticCFunction`. We probably can even file a language proposal to support our use-case.

Something like:

```kotlin
fun foo(m: static () -> Unit)
```

Another advantage of this approach is that we can provide type hints in a type-safe and compatible way. When I say `compatible` it means a hint can only be used for a specific type (https://docs.godotengine.org/en/3.2/getting_started/scripting/gdscript/gdscript_exports.html). The `String` type for example can be used as filesystem paths:

excerpt:
```gdscript
# String is a path to a file.
export(String, FILE) var f
# String is a path to a directory.
export(String, DIR) var f
# String is a path to a file, custom filter provided as hint.
export(String, FILE, "*.txt") var f

# Using paths in the global filesystem is also possible,
# but only in scripts in "tool" mode.

# String is a path to a PNG file in the global filesystem.
export(String, FILE, GLOBAL, "*.png") var tool_image
# String is a path to a directory in the global filesystem.
export(String, DIR, GLOBAL) var tool_dir

# The MULTILINE setting tells the editor to show a large input
# field for editing over multiple lines.
export(String, MULTILINE) var text
```

We can do:

```kotlin
val globalPath by property<String>(hint = PropertyHint.file(global = true)) { ... }
val localPathWithFilter by property<String>(hint = PropertyHint.file(filter = "*.png")) { ... }

// sensible defaults, hint = PropertyHint.string()
val onelineString by property<String> { ... }
// multiline string
val multilineString by property<String>(hint = PropertyHint.string(true)) { ... }
```

2020-03-15 11:01 UTC, chippmann commented
Interesting idea. I quite like it, but i need to think a bit more about it. One immediate question arises though: how do you define the default value when using:
```
@RegisterProperty
val myProperty by property<Int> { ... }
```

2020-03-15 11:02 UTC, chippmann commented
Of course we could define it as an additional param but i personally don't quite like it.

2020-03-15 11:54 UTC, raniejade commented
It's the return value of the lambda.

```kotlin
val myProperty by property<Int> { 1 }
```

It might be easier to check via the compiler plugin if the lambda is capturing or not. (maybe via `LambdaUtil.isCapturingLambda(...)`). What we want here is a non-capturing one.

2020-04-25 08:30 UTC, chippmann commented
Closed in favor of new implementation in master-merge for new binding

2020-04-25 08:30 UTC, closed without merging