Fix bindings wrong constructor call
utopia-rise/godot-kotlin pull request #64
Opened 2020-03-10 08:57 UTC by piiertho

Fix super constructor call using old class name as godot only knows its class names.
This resolves #57 
@chippmann should I update versions here or I let you do it in your PR ?

2020-03-10 14:53 UTC, chippmann commented
@piiertho Depending on how fast one or the other gets merged.
I would say you can also bumpt the version and the faster wins and the other has to rebase ;-)

2020-03-10 14:56 UTC, chippmann requested changes
I'm fine with it. Thanks for the fix.
Please bump the version as stated in my comment :-)

2020-03-11 12:51 UTC, piiertho commented
Done !
I did not updated getting started as I think it should stay with released version.

2020-03-11 15:41 UTC, chippmann commented
> Done !
> I did not updated getting started as I think it should stay with released version.

I personally don't agree as the readme should reflect the sate of the commit
so if one needs a documentation for a specific version, he can look at the readme from the releases tag.
But we maybe should add a link to the master readme where it links to all the releases readme's

2020-03-12 06:58 UTC, piiertho commented
@chippmann that's a good idea ! I do this on lunch time.

2020-03-12 12:23 UTC, chippmann approved these changes
I'm fine with it now. Thanks for the change!
Regarding the change in the readme heading: Do it or leave it ^^ Your choice. I would change the title but with this it's fine as well i think.

2020-03-12 12:23 UTC, chippmann commented on README.md
> +## Release README
I would say it's more a `Release Documentations` or `Documentation for Releases`

2020-03-13 08:06 UTC, merged