Feature/api code generation as gradletask
utopia-rise/godot-kotlin pull request #87
Opened 2020-04-01 07:40 UTC by piiertho

This resolves #86 
It add api code generation, code will not compile as it is missing core types.
Also the api code generation would be changed during merge.
It setups source sets for `godot-library`.

2020-04-01 07:47 UTC, raniejade requested changes
Looking, got a few comments and I think a few files in `.idea` is accidentally committed? `.idea/artifacts/*` for example.

2020-04-01 07:47 UTC, raniejade commented on buildSrc/src/main/kotlin/godot/codegen/Argument.kt
> +        @Json(name = "name")
indentation feels a bit odd, should this be 4 spaces instead of 8?

2020-04-01 07:47 UTC, raniejade commented on buildSrc/src/main/kotlin/godot/codegen/Class.kt
> +        @Json(name = "name")
same here (odd indentation)

2020-04-01 14:00 UTC, chippmann requested changes
I didn't look at the actual codeGen logic yet (I would still wait until it compiles with the actual merge).
But one question about it: am i blind or didn't you yet add the changes regarding inline classes that we talked about on discord?

2020-04-01 14:00 UTC, chippmann commented on buildSrc/build.gradle.kts
> +    implementation("com.beust:klaxon:3.0.1") //5.2
This version is extremely old (you see the commented 5.2. I did this when we where taking over the project. This was the current version back then). I would at least update it to the current version. But personally i would rather use something more well known like Gson, Moshi or jackson

2020-04-01 14:00 UTC, chippmann commented on buildSrc/build.gradle.kts
> +    implementation("com.squareup:kotlinpoet:1.5.0")
I would add the const variable in that file as well and add the comment there as well (even though it's not used at the moment. Just so the person that adds that const variable could forget that this exists or simply don't know.

2020-04-01 14:00 UTC, chippmann commented on buildSrc/src/main/kotlin/godot/codegen/Class.kt
> +        @Json(name = "name")
In this case the indentation comes from the fact that the closing bracket of the constructor is not on a new line. That was probably also the case on the one above but the file wasn't auto formatted afterwards.
@piiertho I suggest that you activate the checkbox "format code" inside the commit dialog in Intellij  so you don't have to remember to format each file :-)

2020-04-01 14:00 UTC, chippmann commented on godot-kotlin/godot-library/build.gradle.kts
> +//    mingwX64("windows")
Targets are commented

2020-04-01 14:00 UTC, chippmann commented on godot-kotlin/godot-library/src/main/nativeInternal/kotlin/godot/internal/Utils.kt
> +internal fun getMB(cl: String, m: String): CPointer<godot_method_bind> {
Please call it `getMethodBind` ^^ At first glance i always think "What? what MB? how many MB's? get 50 MB's of ram or what?" xD

2020-04-01 14:00 UTC, chippmann commented on godot-kotlin/godot-library/src/main/nativeInternal/kotlin/godot/internal/Utils.kt
> +internal fun getMB(cl: String, m: String): CPointer<godot_method_bind> {
Also pleas write out the parameter names

2020-04-01 14:00 UTC, chippmann commented on godot-kotlin/godot-library/src/main/nativeInternal/kotlin/godot/internal/Utils.kt
> +internal fun getSingleton(cl: String, clOld: String): COpaquePointer {
please write out the parameter names

2020-04-01 14:00 UTC, chippmann commented on godot-kotlin/godot-library/src/main/nativeInterop/cinterop/registrations.h
> +#ifndef WRAPPER_REGISTRATIONS_H
why do we still need this file?

2020-04-01 14:00 UTC, chippmann commented on godot-kotlin/godot-library/src/main/nativeInterop/cinterop/godot.def
> +headers = gdnative_api_struct.gen.h registrations.h
same question: why do we still need the registrations.h file?

2020-04-01 15:18 UTC, piiertho commented on godot-kotlin/godot-library/build.gradle.kts
> +//    mingwX64("windows")
oops, missed this

2020-04-02 15:40 UTC, piiertho commented
I close this one, it will be seperated into two PR, one for source sets #88 and one for api code generation.

2020-04-02 15:40 UTC, closed without merging